server:
  port: 8081
spring:
  application:
    name: server-config
  http:
    encoding:
      enabled: true
      charset: UTF-8
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/

eureka:
   client:
     serviceUrl:
      defaultZone: http://discovery.agile.dev:8082/eureka/
