server:
  port: 8082
spring:
  application:
    name: server-discovery
eureka:
  instance:
    hostname: agile.dev
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/





