server:
  port: 8082
spring:
  application:
    name: server-discovery
  jmx:
    enabled: false
eureka:
  instance:
    hostname: agile.test
    environment: prod
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
